# Generated by Django 5.1.2 on 2024-10-11 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='data_nascimento',
            field=models.DateField(db_column='data_nascimento', null=True),
        ),
    ]
