# Generated by Django 5.1.2 on 2024-10-15 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em andamento', 'Em Andamento'), ('concluido', 'Concluído')], default='pendente', max_length=20)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('caso_clinico', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clinica.casoclinico')),
                ('fisioterapeuta', models.ForeignKey(limit_choices_to={'user_type': 'FIS'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='solicitacoes_fisioterapeuta', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(limit_choices_to={'user_type': 'PAC'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='solicitacoes_paciente', to=settings.AUTH_USER_MODEL)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clinica.servico')),
            ],
            options={
                'db_table': 'solicitacao_atendimento',
            },
        ),
    ]
