# Generated by Django 5.1.2 on 2024-10-11 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_alter_user_data_nascimento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True, 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
