# Generated by Django 5.1.2 on 2024-10-09 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_fisioterapeuta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('especialidade', models.CharField(db_column='especialidade', max_length=100)),
            ],
            options={
                'db_table': 'servico',
            },
        ),
        migrations.CreateModel(
            name='CasoClinico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('descricao', models.TextField(db_column='descricao')),
                ('fisioterapeuta', models.ForeignKey(db_column='fisioterapeuta_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='casos_clinicos', to='clinica.fisioterapeuta')),
                ('paciente', models.ForeignKey(db_column='paciente_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='casos_clinicos', to='clinica.paciente')),
                ('servico', models.ForeignKey(db_column='servico_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='casos_clinicos', to='clinica.servico')),
            ],
            options={
                'db_table': 'caso_clinico',
            },
        ),
    ]
