# Generated by Django 5.1.2 on 2024-10-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0004_user_minibio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoatendimento',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Em andamento', 'Em Andamento'), ('Concluído', 'Concluído')], default='Pendente', max_length=20),
        ),
    ]
